version: 1.0.{build}
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - oliver@grobs.de
  subject: Choco Paket mit AU und AppVeyor
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
